tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "sanemat/font"
brew "anyenv"
brew "python"
brew "go"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "grep"
brew "jq"
brew "kubernetes-cli"
brew "neovim"
brew "rename"
brew "tig"
brew "vim"
brew "zsh"
brew "sanemat/font/ricty", args: ["with-powerline"]

