version: 2
  
tools:
  javascript-eslint: &javascript-eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  javascript-prettier: &javascript-prettier
    format-command: './node_modules/.bin/prettier --parser typescript'

languages:
  javascript:
    - <<: *javascript-eslint
    - <<: *javascript-prettier

  typescript:
    - <<: *javascript-eslint
    - <<: *javascript-prettier

