set nocompatible

" Set the runtime path to $XDG_DATA_HOME/vim
let data_dir = $XDG_DATA_HOME ? $XDG_DATA_HOME . '/vim' : $HOME . '/.local/share/vim'
" Add data_dir as first path in the runtimepath
execute 'set runtimepath^=' . data_dir

" Install vim-plug if not already installed
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin(data_dir . '/plugged')

" fzf
Plug 'junegunn/fzf.vim'
Plug '/opt/homebrew/opt/fzf'

" theme
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'vim-airline/vim-airline'

" lsp
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

call plug#end()

" theme
set termguicolors
syntax enable
let g:dracula_italic = 0
colorscheme dracula
let g:airline_theme='dracula'

set noswapfile
set hidden
set relativenumber number
set grepprg=rg\ --vimgrep\ --smart-case\ --follow

filetype plugin on

let mapleader = "\<Space>"

" file search
nnoremap <silent> <Leader>b :Buffers<CR>
nnoremap <silent> <C-p> :Files<CR>
nnoremap <silent> <Leader>f :Rg<CR>
nnoremap <silent> <Leader>/ :BLines<CR>
nnoremap <silent> <Leader>' :Marks<CR>
nnoremap <silent> <Leader>g :Commits<CR>
nnoremap <silent> <Leader>H :Helptags<CR>
nnoremap <silent> <Leader>hh :History<CR>
nnoremap <silent> <Leader>h: :History:<CR>
nnoremap <silent> <Leader>h/ :History/<CR>

