shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
env_asdf_dir = "export ASDF_DIR=\"{{ dir }}\""

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["defer"]

[plugins.asdf]
github = "asdf-vm/asdf"
use = ["asdf.sh"] # To prevent loading unnecessary files by default glob pattern matching
hooks.pre = """
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
"""
apply = ["env_asdf_dir", "defer"] # Define ASDF_DIR before source asdf.sh

## local plugins
[plugins.fzf]
local = "~/.config/zsh"
use = ["fzf.zsh"]
apply = ["defer"]

# Do not apply defer to load synchronously
[plugins.prompt]
local = "~/.config/zsh"
use = ["prompt.zsh"]

# the `apply` field is not supported by inline plugins
[plugins.compinit]
inline = """
autoload -Uz compinit
zsh-defer compinit -d "${XDG_CACHE_HOME}/zsh/zcompdump"
"""
